wapiti-scanner/wapiti

tests/attack/test_mod_backup.py, tests/attack/test_mod_nikto.py, tests/attack/test_mod_shellshock.py, tests/attack/test_mod_ssrf.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_ssrf.py, wapitiCore/attack/mod_xxe.py, wapitiCore/main/getcookie.py, wapitiCore/net/__init__.py, wapitiCore/net/crawler.py, wapitiCore/net/jsparser/jsparser3.py, wapitiCore/net/sqlite_persister.py, wapitiCore/report/htmlreportgenerator.py
Use autopep8 to correct some coding style
=> Fix some coding style

.github/workflows/main.yml, .pylintrc
Create GitHub Actions to run `setup.py test --vv` on differents python versions and PyLint
=> Create GitHub actions

wapitiCore/moon.py
Fix wapitiCore/ snake_case pylint messages from moon.py (short variable names)
=> Fix wapitiCore/ snake_case pylint messages from moon.py

wapitiCore/net/lamejs.py, wapitiCore/net/sqlite_persister.py, wapitiCore/net/swf.py, wapitiCore/net/web.py
Fix wapitiCore/net/ snake_case pylint messages (short variable names) and some wrong hanging indentation
=> Fix wapitiCore/net/ snake_case pylint messages

wapitiCore/net/jsparser/jsparser3.py
Fixing all pylint "snake_case" errors on file /wapitiCore/net/jsparser/jsparser3.py
=> Fix all  snake_case errors on file /wapitiCore/net/jsparser/jsparser3.py

MANIFEST.in, Pipfile, setup.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_wapp.py, wapitiCore/language/vulnerability.py, wapitiCore/net/crawler.py, wapitiCore/net/jsoncookie.py, wapitiCore/report/jsonreportgenerator.py, wapitiCore/report_template/report.html, wapitiCore/wappalyzer/data/apps.json, wapitiCore/wappalyzer/wappalyzer.py
Add wappalyzer attack module :  web technology detection (with versions and categories).
Fix setup.py, Pipefile, MANIFEST.in and attack.py to support the new mod_wapp module.
Fix undefined variable in crawler.py.
=> Add wappalyzer attack module

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Add test file test_mod_wapp.py for wapp module.
Fix issues in mod_wapp.py and wappalyzer.py.
Ignore warning generated by ApplicationData on regex parsing failure.
=> Add test_mod_wapp.py for wapp module

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Fix mod_wapp and test issues due to changes in wappalyzer project (apps.json renamed, apps replaced by technologies, script replaced by scripts).
=> Fix mod_wapp and test issues due to changes in wappalyzer project

.dockerignore, Dockerfile
Add production dockerfile to have the minimal container to run wapiti.
=> Add production dockerfile

.github/workflows/main.yml, .pylintrc
This PR resolve the pylint errors
=> Fix pylint errors

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Edit mode wappalyzer output, adding "name" attribute to "info"
=> Edit "mod_wapp" output

tests/attack/test_mod_nikto.py, tests/attack/test_mod_wapp.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_wapp.py, wapitiCore/main/wapiti.py, wapitiCore/net/sqlite_persister.py
Add a new option --store-config to change the default directory path to store apps.json and nikto_db files.
=> Add --store-config option

wapitiCore/wappalyzer/wappalyzer.py
Change normalization method in wappalyzer to support generic format in apps.json.
For "cookies", "meta" and "headers", we now support the following list format :
`{"meta" : {"generator": ["test1", "test2"]}}` instead of only `{"meta" : {"generator": "test1"}}`
=> Fix wappalyzer to support new format in apps.json

README.md
Adding the new modules to the file README.md
=> Add the new modules names to README.md

INSTALL.md, README.md, doc/wapiti.ronn
Update Python version requirement in INSTALL.md.
Add new module names (wapp, csrf), add GET/POST authentication on login forms in README.md.
Add new options (--update, --store-config), fix -s, --auth-type, -a descriptions in wapiti.ronn.
=> Update INSTALL.md, README.md and wapiti.ronn

wapitiCore/attack/mod_ssrf.py
=> Fix endpoint issue in ssrf module

wapitiCore/attack/mod_backup.py, wapitiCore/attack/mod_blindsql.py, wapitiCore/attack/mod_brute_login_form.py, wapitiCore/attack/mod_crlf.py, wapitiCore/attack/mod_csrf.py, wapitiCore/attack/mod_exec.py, wapitiCore/attack/mod_file.py, wapitiCore/attack/mod_htaccess.py, wapitiCore/attack/mod_redirect.py, wapitiCore/attack/mod_sql.py, wapitiCore/attack/mod_ssrf.py, wapitiCore/attack/mod_xss.py, wapitiCore/language/vulnerability.py
Update the level of detected vulnerabilities
Adding "CRITICAL_LEVEL" and "INFO_LEVEL" values
=> Update "Level" of detected vulnerabilities

tests/attack/test_mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Fix issue in wappalyzer due to lazy evaluation for boolean expressions.
=> Fix version detection issue in wappalyzer

doc/AUTHORS
=> Add AUTHORS

doc/wapiti.1
Fix some additional typos, from Sophie Brun <sophie@freexian.com>
=> Update wapiti.1 fixing some typos

setup.cfg, setup.py, tests/web/test_crawl.py, tests/web/test_explorer.py, tests/web/test_request.py, wapitiCore/attack/attack.py, wapitiCore/main/wapiti.py, wapitiCore/net/crawler.py, wapitiCore/net/web.py
=> Fix load and save crawl state + add test

Dockerfile.test
The Dockerfile.test behavior was too different from github actions one.
=> Update Dockerfile.test to be closer from github actions behavior

.github/workflows/main.yml, Dockerfile.test, tests/web/test_explorer.py, wapitiCore/net/crawler.py
Refactor Explorer.explore, put links and forms extraction in a new method
+ test for this method
+ prevent github CI from installing recommended packages
=> Refactor Explorer.explore, put links and forms extraction in a new method

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py, wapitiCore/definitions/fingerprint_webapp.py, wapitiCore/language_sources/en.po, wapitiCore/language_sources/fr.po
Fix https://github.com/wapiti-scanner/wapiti/issues/66
The wapp module now raises a level_info vulnerability for web applications detected with a version (WSTG-INFO-08).
Add tests for fingerprint web server and fingerprint web app.
=> Add fingerprint web app in vulnerabilties

README.rst
Reformat title and add data regarding author and sponsors
=> Add creation and sponsoring information

tests/attack/test_mod_wp_enum.py, wapitiCore/attack/mod_wp_enum.py
Adding "test_mod_wp_enum.py" file
=> Adding unit test file for the Wordpress module

Makefile, setup.py
Fix https://github.com/wapiti-scanner/wapiti/issues/107
=> Exclude tests from package in setup.py

Pipfile, setup.py, tests/web/test_explorer.py, wapitiCore/net/crawler.py, wapitiCore/net/jsparser_angular.py
Add basic js parser for angular : extract related domains and paths.
Add brotli module in requirements to support br content-encoding, this will help to detect more js files.
=> Add js parser for angular

tests/attack/test_mod_nikto.py, wapitiCore/attack/mod_nikto.py, wapitiCore/main/wapiti.py
Leverage asyncio Tasks to submit requests concurently for mod_nikto
=> Concurrency for mod_nikto

wapitiCore/attack/attack.py, wapitiCore/attack/mod_backup.py, wapitiCore/attack/mod_buster.py, wapitiCore/attack/mod_crlf.py, wapitiCore/attack/mod_exec.py, wapitiCore/attack/mod_file.py, wapitiCore/attack/mod_methods.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_permanentxss.py, wapitiCore/attack/mod_redirect.py, wapitiCore/attack/mod_sql.py, wapitiCore/attack/mod_ssrf.py, wapitiCore/attack/mod_timesql.py, wapitiCore/attack/mod_wapp.py, wapitiCore/attack/mod_wp_enum.py, wapitiCore/attack/mod_xss.py, wapitiCore/attack/mod_xxe.py, wapitiCore/main/log.py, wapitiCore/main/wapiti.py, wapitiCore/net/crawler.py
Force to load and configure logging each time the logging object is imported.
Fixes #147
=> Configure logging for all tests

doc/FAQ.md
Changed "your owns" by "your own"
=> Grammar typo

tests/attack/test_mod_backup.py, wapitiCore/attack/mod_backup.py
=> mod_backup: check for false positives inside must_attack()

tests/attack/test_mod_sql.py, wapitiCore/attack/mod_sql.py
mod_sql: change order of boolean tests to prevent false-positives (Moodle case)
Fix #158
=> mod_sql: change order of boolean tests to prevent false-positives

tests/attack/test_mod_nikto.py, wapitiCore/attack/mod_buster.py, wapitiCore/attack/mod_nikto.py, wapitiCore/net/web.py
=> Fix Nikto false positives that are relying only on status code

make_exe.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_brute_login_form.py, wapitiCore/attack/mod_drupal_enum.py, wapitiCore/attack/mod_file.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_permanentxss.py, wapitiCore/attack/mod_takeover.py, wapitiCore/attack/mod_wapp.py, wapitiCore/attack/mod_wp_enum.py, wapitiCore/attack/mod_xss.py, wapitiCore/attack/mod_xxe.py, wapitiCore/main/wapiti.py, wapitiCore/net/jsoncookie.py, wapitiCore/net/xss_utils.py, wapitiCore/report/htmlreportgenerator.py, wapitiCore/report/jsonreportgenerator.py, wapitiCore/report/xmlreportgenerator.py, wapitiCore/wappalyzer/wappalyzer.py
Hello, in this pull request I have fixed three linting errors:
- line-too-long
- redefined-argument-from-local
- unspecified-encoding
=> Fix lint: line-too-long & redefined-argument-from-local & unspecified-encoding

Pipfile, Pipfile.lock, setup.py, wapitiCore/main/wapiti.py
Fix #189 
SOCKS support seems better
=> Upgrade httpx and httpx-socks versions

tests/cli/test_options.py, wapitiCore/attack/attack.py, wapitiCore/main/wapiti.py
Added a passive mode with these modules:
- cookieflags
- csp
- http_headers
- wapp
It is launched by writing `passive` as an argument to the module list.  
Example: `wapiti -u http://foobar/ -m passive`  
#157 Passive mode
=> Added a passive mode to only execute nonharmful modules

tests/cli/test_options.py, tests/reports/test_reports.py, wapitiCore/language_sources/de.po, wapitiCore/language_sources/en.po, wapitiCore/language_sources/es.po, wapitiCore/language_sources/fr.po, wapitiCore/language_sources/ms.po, wapitiCore/language_sources/pt.po, wapitiCore/language_sources/template.po, wapitiCore/language_sources/zh.po, wapitiCore/main/wapiti.py, wapitiCore/report/htmlreportgenerator.py, wapitiCore/report/reportgenerator.py, wapitiCore/report/txtreportgenerator.py, wapitiCore/report/xmlreportgenerator.py, wapitiCore/report_template/report.html
In this pull request, I have added the number of crawled pages in the info section of the report.
#197
=> Added the number of crawled pages in the info section of the report

tests/net/test_crawler.py, wapitiCore/main/wapiti.py, wapitiCore/net/crawler.py
In this pull request, the post auth system has been improved by:
- adding the keyword `signoff` to the disconnect detection regex
- by excluding automatically the disconnect url
#198
=> Improved the post auth system by excluding automatically the disconnect url

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py
Before this pull request, the Wapp module was detecting technologies and their versions only on the redirection of the root URL.  
For instance, if the URL `https://test.com` redirects to `https://test.com/login/` and we decide to do an analysis on `https://test.com` it will in reality do an analysis on `https://test.com/login/`.
Sometimes, some headers are not transferred to the redirected URL, so we can lose precision on versions or in the worst case miss a technology.
In this pull request, the Wapp module is now doing an analysis on the root URL and also on the redirected URL. After that, it merges both results.  
The issue has been detected on this URL: https://216.176.178.100/owa/ the header `X-OWA-Version` is disappearing during the redirection.
N/A
=> Now the wapp module will detect all the technologies on the root url and on the redirected one

.github/workflows/main.yml, Dockerfile.test, setup.py, tests/cli/test_options.py, tests/data/httpbin.php, tests/web/test_request.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_backup.py, wapitiCore/attack/mod_brute_login_form.py, wapitiCore/attack/mod_buster.py, wapitiCore/attack/mod_csrf.py, wapitiCore/attack/mod_htaccess.py, wapitiCore/attack/mod_log4shell.py, wapitiCore/attack/mod_methods.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_shellshock.py, wapitiCore/attack/mod_wapp.py, wapitiCore/attack/mod_wp_enum.py, wapitiCore/main/wapiti.py
Prevent loading modules if they weren't  selected and cach ImportError silently if they are missing
=> Improve handling of modules 

wapitiCore/net/page.py
Added a new exception to be caught in the function `json` of the class Page.
#219
=> Added a new exception to be caught in the function json

wapitiCore/net/crawler.py
Added a missing return element in the function `_async_try_login_basic_digest_ntlm`
#218
=> Added missing return element

tests/attack/test_mod_log4shell.py, wapitiCore/attack/mod_log4shell.py
Added tests for the Log4Shell module.
N/A
=> Added tests for the Log4Shell module

tests/attack/test_mod_htp.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_htp.py, wapitiCore/language_sources/de.po, wapitiCore/language_sources/en.po, wapitiCore/language_sources/es.po, wapitiCore/language_sources/fr.po, wapitiCore/language_sources/ms.po, wapitiCore/language_sources/pt.po, wapitiCore/language_sources/template.po, wapitiCore/language_sources/zh.po
This pull request implements a new module to scan web technologies using the Hash The Planet database.  
This implementation doesn't any need external libraries. To be merged, it needs first to set up a link to download the database.  
N/A
=> Added a new module to scan web technologies using the HashThePlanet database

wapitiCore/net/crawler.py
Fix https://github.com/wapiti-scanner/wapiti/issues/241
=> Allows Wapiti to work with bad ssl/tls procotols

wapitiCore/report/htmlreportgenerator.py, wapitiCore/report_template/report.html
To sum up:
```python
if level == CRITICAL_LEVEL:
return "🔥"
if level == HIGH_LEVEL:
return "🔴"
if level == MEDIUM_LEVEL:
return "🟠"
if level == LOW_LEVEL:
return "🟡"
if level == INFO_LEVEL:
return "🕵️"
```
and for anomalies (like HTTP 500 errors) : 🤕
=> Use unicode emojis to show vulnerability level

wapitiCore/attack/mod_drupal_enum.py
Removed an unused variable from the drupal_enum attack file
fixes #239
=> Removed an unused variable from the drupal_enum attack file

wapitiCore/net/sql_persister.py
=> Fix httpx.Response object creation in sql_persister.py

tests/attack/test_mod_xss_advanced.py, tests/data/xss/iframe_src_htmlentities.php, tests/data/xss/link_href_htmlentities.php, tests/data/xss/link_href_strip_tags.php, wapitiCore/data/attacks/xssPayloads.ini, wapitiCore/net/xss_utils.py
Additional XSS detection, two cases that I've seen ITW.
```
<a href="CONTROL">anything</a>
<iframe src="CONTROL"></iframe>
```
xss_utils change was made in a way to avoid doing a lot of touching on that section. comments welcome.
=> Added iframe and anchor src/href direct control

wapitiCore/report/jsonreportgenerator.py
=> Fix JSON report generation with detailed report option

tests/cookies/test_conversion.py
(from headless browser or intercepting proxy)
=> add tests for cookie conversion 

tests/cli/test_options.py, wapitiCore/main/wapiti.py
should fix handling of -a -and --form-cred options following refactoring
=> fix auth creds option handling

wapitiCore/net/intercepting_explorer.py
=> Fix issue #366

tests/attack/test_mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Add wappalyzer dom detection and unit test about it
=> Add wappalyzer dom detection and unit test about it

wapitiCore/net/sql_persister.py
Fix pylint sqlalchemy not-callable erorrs on func.max and func.count.
=> Fix pylint sqlalchemy not-callable errors

tests/attack/test_mod_log4shell.py, wapitiCore/attack/mod_log4shell.py
Add UniFi payload in log4shell module.
=> Adding UniFi into log4shell module

pyproject.toml, wapitiCore/attack/mod_ssl.py, wapitiCore/controller/wapiti.py
+ add more info on module import error
=> put "ssl" extra dependencies in pyproject 

wapitiCore/net/crawler.py
=> Fix overwriting post headers

Dockerfile.endpoint, Makefile
So users don't have to setup apache + php with url rewriting and permissions themselves
=> Add a dockerfile allowing to quickly setup the endpoint

.github/workflows/main.yml
Fix error in code style analysis in github workflow
=> Fix code style analysis

tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
=> Add CPE output to wappalyzer

tests/attack/test_mod_wapp.py
Fix cpe test issues due to new technologies.json file from wapp.
=> Fix cpe test issues

tests/attack/test_mod_upload.py, tests/web/test_scope.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_upload.py, wapitiCore/controller/wapiti.py, wapitiCore/definitions/unrestricted_upload.py, wapitiCore/main/wapiti.py, wapitiCore/net/explorer.py, wapitiCore/net/intercepting_explorer.py, wapitiCore/net/scope.py
* adds module to test for unrestricted file uploads by sending PHP file with several extensions
* fix how excluded urls were used (was some old code left after refactoring)
* pass excluded urls through attack options so the module doesn't attempt to fetch those urls
=> Add module for Unrestricted uploads vulnerability

tests/attack/test_mod_spring4shell.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_spring4shell.py, wapitiCore/definitions/spring4shell.py
Based on @bretfourbe 's work. #275 
I changed the detection method to be less aggressive and also added unit test.
=> Add module spring4shell

tests/integration/docker-compose.setup.yml, tests/integration/endpoint/Dockerfile, tests/integration/run.sh, tests/integration/test_mod_ssrf/assertions/check.sh, tests/integration/test_mod_ssrf/assertions/smart_checker.py, tests/integration/test_mod_ssrf/assertions/ssrf.json, tests/integration/test_mod_ssrf/php/src/index.php, tests/integration/test_mod_ssrf/php/src/ssrf.php, tests/integration/wapiti/modules.json
This MR is for inserting integration tests scenario for the ssrf module.
Since its report contains data that can vary but is still needed, the check§.sh calls an external python script for a better analysis.
As it is also needed to check ssrf vulns, an endpoint has been added
=> Test ssrf module

tests/integration/docker-compose.setup.yml, tests/integration/endpoint/Dockerfile, tests/integration/run.sh, tests/integration/test_mod_xxe/Dockerfile, tests/integration/test_mod_xxe/assertions/check.sh, tests/integration/test_mod_xxe/assertions/smart_checker.py, tests/integration/test_mod_xxe/assertions/xxe.json, tests/integration/test_mod_xxe/php/src/index.php, tests/integration/test_mod_xxe/php/src/xml_vuln_maker.php, tests/integration/wapiti/modules.json
Integration tests for the xxe module
=> Tests XXE module

doc/ChangeLog_Wapiti, wapitiCore/attack/mod_spring4shell.py
fix https://github.com/wapiti-scanner/wapiti/issues/477
=> Set name attribute on spring4shell module

Makefile
makefile additions for the integration test system
=> added integration commands for the makefile

INSTALL.md, README.rst
Change the installation doc with the new way with the `pyproject.toml` file.
Cf issue #486
=> Change doc to fit with the new installation way.

tests/web/test_scope.py, wapitiCore/net/scope.py, wapitiCore/parsers/commandline.py
Add subdomain for scope option and unit test
=> Add subdomain scope option and unit test

tests/attack/test_mod_buster.py, tests/attack/test_mod_exec.py, tests/attack/test_mod_file.py, tests/attack/test_mod_nikto.py, tests/attack/test_mod_timesql.py, tests/data/time_sql.php
Adapting the max_attack_time functions to test the comportment of the module when the time_max option is set, by simulating the time of response for the vulnerable requests
=> Fix tests max_attack_time

tests/attack/test_mod_log4shell.py, tests/attack/test_mod_sql.py, wapitiCore/attack/mod_log4shell.py, wapitiCore/attack/mod_sql.py
Add max attack time option on SQL and log4shell modules.
Fix issue #516
=> Add max attack time option on SQL and log4shell modules

tests/attack/test_mod_file.py, wapitiCore/attack/mod_file.py
Fix an error in file module when an open redirect vulnerability were found.
=> Fix lfi with open redirect

tests/cli/test_options.py, wapitiCore/main/wapiti.py
Fix https://github.com/wapiti-scanner/wapiti/issues/528
=> fix none args.modules case

wapitiCore/attack/mod_log4shell.py
Add except for log4shell module.
Timeout on dns serveur and host unreachable.
=> add except for log4shell

wapitiCore/attack/mod_exec.py, wapitiCore/data/attacks/execPayloads.ini
As asked in #499 by @devl00p, removal of the preg_replace heuristic
=> removed the preg_replace heuristic

tests/cli/test_options.py, wapitiCore/controller/wapiti.py
Fix https://github.com/wapiti-scanner/wapiti/issues/537
=> add test for max-attack-time

wapitiCore/attack/mod_sql.py
Add a verification to make sure that the parameter exists before injecting the payload.
close #546
=> Fix issue #546

tests/attack/test_mod_wapp.py, tests/cli/test_options.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_wapp.py, wapitiCore/main/wapiti.py, wapitiCore/parsers/commandline.py
Adding  the "--wapp-url" option to customise the update URL of the Wappalyzer database
=> Add an option for Wapp module and update

doc/wapiti.1, doc/wapiti.1.html, doc/wapiti.ronn, wapitiCore/parsers/commandline.py
Ordering scope parameters orders.
It is the PR #530 but in one comit.
=> Ordering scope parameters orders

tests/attack/test_mod_wapp.py, tests/cli/test_options.py, wapitiCore/attack/mod_wapp.py, wapitiCore/controller/wapiti.py, wapitiCore/main/wapiti.py, wapitiCore/parsers/commandline.py
=> Fix the issue #559

tests/attack/test_mod_network_device.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_network_device.py
Add a module to detect network devices with version when possible
=> Add module for network devices

tests/attack/test_mod_wapp.py, tests/cli/test_options.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_wapp.py, wapitiCore/main/wapiti.py, wapitiCore/parsers/commandline.py
add an option "wapp-dir" for  to update the wapp database from local files
=> Add a "wapp-dir" option

tests/attack/test_mod_cms.py, wapitiCore/attack/cms/mod_joomla_enum.py
=> Fix issue #570

tests/integration/wapiti/templates_and_data.py, tests/integration/wapiti/test.py, tests/reports/test_reports.py, wapitiCore/controller/wapiti.py, wapitiCore/main/wapiti.py, wapitiCore/net/sql_persister.py, wapitiCore/parsers/commandline.py, wapitiCore/report/htmlreportgenerator.py, wapitiCore/report/jsonreportgenerator.py, wapitiCore/report/reportgenerator.py, wapitiCore/report/txtreportgenerator.py, wapitiCore/report/xmlreportgenerator.py
Add a level to  choose  the verbosity of the detailed report
=> Add a level to -dr option

pyproject.toml, tests/cli/test_options.py, tests/data/complexe_swagger.json, tests/data/openapi.json, tests/data/swagger.json, tests/data/swagger.yaml, tests/parsers/test_swagger_parser.py, wapitiCore/main/wapiti.py, wapitiCore/parsers/commandline.py, wapitiCore/parsers/swagger.py
Adding `--swagger` option to import API routes into Request object with its parameters to perform a scan.
=> Adding Swagger option

wapitiCore/main/wapiti.py
Fix exception handling in main wapiti
=> Fix exception handling in main wapiti

tests/attack/test_mod_network_device.py, wapitiCore/attack/mod_network_device.py, wapitiCore/attack/network_devices/mod_forti.py, wapitiCore/attack/network_devices/mod_ubika.py
Add Fortinet products detection for module network_device
=> Add Fortinet detection

wapitiCore/controller/wapiti.py, wapitiCore/net/intercepting_explorer.py
=> Fix max-scan-time and missing timeout in headless explorer

tests/attack/test_mod_network_device.py, wapitiCore/attack/mod_network_device.py, wapitiCore/attack/network_devices/mod_harbor.py
Add Harbor detection for module network_device.
=> Add Harbor Detection

tests/attack/test_mod_network_device.py, wapitiCore/attack/mod_network_device.py, wapitiCore/attack/network_devices/mod_forti.py, wapitiCore/attack/network_devices/mod_harbor.py, wapitiCore/attack/network_devices/mod_ubika.py, wapitiCore/attack/network_devices/network_device_common.py
Add network_device_common class and fix network_device modules for consistency with cms for instance.
=> Add network_device_common class and fix for consistency

tests/attack/test_mod_network_device.py, wapitiCore/attack/mod_network_device.py, wapitiCore/attack/network_devices/mod_citrix.py, wapitiCore/attack/network_devices/network_device_common.py
Add Citrix products detection for module network_device
=> Add Citrix to mod_network_device

tests/cli/test_options.py, tests/data/openapi.yaml, tests/parsers/test_swagger_parser.py, wapitiCore/parsers/swagger.py
Remove exit on swagger errors
Try to continue parsing as much as possible even when errors occur
Fix https://github.com/wapiti-scanner/wapiti/issues/586
Add test case
=> Remove exit on swagger errros, add test case

wapitiCore/attack/mod_wapp.py
Fix headless wapp for confidence 0 such as js detection for lodash and underscore.js
Add case for regex starting with `\\;version:`
=> Fix headless wapp for confidence 0

doc/wapiti.1, doc/wapiti.1.html, doc/wapiti.ronn
Add swagger option in wapiti doc
=> Add swagger option in wapiti doc

tests/data/openapi3.yaml, tests/parsers/test_swagger_parser.py, wapitiCore/parsers/swagger.py
Improve Swagger base URL parsing and support openAPI 3.0 url
=> Improve Swagger base URL parsing and support openAPI 3.0

tests/attack/test_mod_wapp.py, tests/cli/test_options.py, wapitiCore/attack/attack.py, wapitiCore/main/wapiti.py, wapitiCore/wappalyzer/wappalyzer.py
We are relying on a fork of wappalyzer that was abandonned one year ago.
Some new projects are trying to maintain the detection database.
I suggest we rely on https://github.com/enthec/webappanalyzer
Tested it and changes are as simple as changing the repo url in our code.
=> Use HTTPArchive/wappalyzer project for mod_wapp

Makefile, tests/attack/test_active_scanner.py, tests/cli/test_options.py, wapitiCore/attack/active_scanner.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_wapp.py, wapitiCore/controller/exceptions.py, wapitiCore/controller/wapiti.py, wapitiCore/main/getcookie.py, wapitiCore/main/wapiti.py
Purpose is to reduce the amount of code in the Wapiti class and have a dedicated class for attack modules management
=> Move attack management to a new ActiveScanner class
