.pylintrc
Disable missing-class-docstring and missing-module-docstring messages in pylint
=> Disable missing-class-docstring and missing-module-docstring in pylint

.github/workflows/main.yml, Dockerfile.test, Pipfile, Pipfile.lock, README.md
Python3.5 end of life : 13 sep 2020
Python3.9 release : 5 oct. 2020
=> Remove support for python3.5 and add support for python3.9

wapitiCore/main/wapiti.py
We should be able to use wapiti even when the URL has no given path.
I am not sure if this is the best way to set the URL path, if you know a better one, please let me know.
=> Wapiti should accept urls without path

tests/attack/test_mod_nikto.py, tests/attack/test_mod_wapp.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
Dependencies can break wapiti. We have detected 2 times where wappalyzer has changed the format of its json file.
For more stability, let's use forks from the nikto and wappalyzer projects.
=> Fix dependencies breaking errors

wapitiCore/main/wapiti.py
Hello,
First, I changed the way '--max-scan-time' works as I don't understand why we apply a '*60' on the argument to force it to be in minutes.
'--max-scan-time' is now in seconds.
Then I added a new arg '--max-attack-time' which cause the module to stop if it's duration is superior.
The good thing is that the vulnerabilities found are not lost and the execution continue normally (the next module is executed with the same 'timeout' constraint)
wapiti-scanner/wapiti-scanner.github.io#1
Close #48
=> Add arg '--max-attack-time'

wapitiCore/main/wapiti.py
I'm trying to normalize the URLs handling because I noticed that like 'URL' before the endpoints arguments does not accept an empty path.
I created a new method 'set_url_path' which add '/' to the url if no path has been set.
I also modified the is_valid_endpoint to is_valid_url which is a method that verify the format of an url.
=> Refactor url handling

wapitiCore/attack/mod_cookieflags.py, wapitiCore/attack/mod_csp.py, wapitiCore/attack/mod_http_headers.py, wapitiCore/definitions/csp.py, wapitiCore/definitions/http_headers.py, wapitiCore/definitions/http_only.py, wapitiCore/definitions/secure_cookie.py
Replace add_anom by add_vuln in http_headers, csp and cookieflags modules.
Change TYPE value in definitions.
=> Move http_headers, csp and cookieflags results in vulnerability

make_exe.py, tests/attack/test_mod_sql.py, tests/attack/test_mod_timesql.py, tests/parsers/test_html_parser.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_sql.py, wapitiCore/attack/mod_timesql.py, wapitiCore/main/wapiti.py, wapitiCore/net/page.py, wapitiCore/net/web.py
Currently Wapiti use two separate modules for SQL injection :
- sql for error-based sql injections
- blindsql for time based sql injections
Both have pros and cons (error-based is very fast but errors are hidden most of the time so detection rate is low while time-based is slow but works with silent errors). A boolean-based module should bring advantages of both:
- it is not that fast but the amount of payloads is reduced compared to time-based, also we don't have to wait for a timeout :+1: 
- works well for blind injection and is more dbms agnostic than time-based (which is using sleep() for mysql and waitfor for mssql for example while other dbms doesn't have such capability)
Also we can move the old blindsql module to a renamed timesql with will be more explicit and make it optional. …
=> Add boolean-based blind SQL injection

MANIFEST.in, setup.py
Some README.md were still present in MANIFEST.in and setup.py, breaking the build process.
=> Fix README.md to README.rst

wapitiCore/main/wapiti.py
FIPS mode is a government standard for encryption, and changing the hashing algorithm from md5 to sha256 here should allow you to run within a FIPS environment.
Curious if there was a reason to use md5 instead of sha256 here. There could also be a flag added into the args but since the hashing is set during init, it would take a bit of rework in that area.
=> Changed hashing for FIPS mode

wapitiCore/attack/mod_permanentxss.py, wapitiCore/attack/mod_xss.py, wapitiCore/data/attacks/xssPayloads.ini, wapitiCore/net/xss_utils.py
XSS modules will use the external endpoint (by default https://wapiti3.ovh/) specified via `--external-endpoint` option.
Replaced all hard coded urls in xssPayloads.ini by [EXTERNAL_ENDPOINT] or [PROTO_ENDPOINT]. 
These values are then replaced in load_payloads_from_ini method (from xss_utils.py) with the external endpoint value when generate_payloads method is called.
Fix https://github.com/wapiti-scanner/wapiti/issues/108
=> Fix xss modules and payloads to support custom endpoints

wapitiCore/main/getcookie.py
When "wapiti-getcookie" detect default values in forms the user have to copy-past those values and put them manually.
This MR fix this problem and "wapiti-getcookie" take thoses values by pressing "Enter" in the interactive terminal
=> Fix problem of detected default values in wapiti-getcookie

wapitiCore/attack/mod_cookieflags.py
Wapiti produces false positive on ASP .Net Core applications. Reason for that is that ASP .Net Core sets HttpOnly cookie parameter in lowercase: 
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/Headers/src/SetCookieHeaderValue.cs#L34
According to [RFC](https://tools.ietf.org/html/rfc6265#section-5.2.6) any cookie flags can be case insensitive 
> If the attribute-name case-insensitively matches the string
"HttpOnly", the user agent MUST append an attribute to the cookie-
attribute-list with an attribute-name of HttpOnly and an empty
attribute-value.
=> Account for lowercase HttpOnly flag.

wapitiCore/attack/mod_xss.py, wapitiCore/main/wapiti.py
The value in some of the xssPayloads is set to  *[EXTERNAL_ENDPOINT]__XSS__z.js*
We replace *__XSS__.js* by the taint but we did not replace the *[EXTERNAL_ENDPOINT]*
This caused us to search for *[EXTERNAL_ENDPOINT]xxxxx.js* instead of *https://wapiti3.ovh/xxxxx.js*
Fix this by replacing *[EXTERNAL_ENDPOINT]* by the external endpoint
=> Fix xss detection

.github/workflows/main.yml, setup.py
Add a new github action which will build the dockerfile to avoid breaking it again in the future.
Im using docker/setup_buildx_actions, which I found in https://docs.docker.com/ci-cd/github-actions/
I also fixed the Dockerfile with https://github.com/wapiti-scanner/wapiti/issues/115#issuecomment-826359573
Resolve #115
=> Add Github Action with docker build

Pipfile, Pipfile.lock, setup.py, tests/attack/test_mod_xxe.py, wapitiCore/net/crawler.py
On a case like this:
```html
<html>                                                                                                                 
<body>                                                                                                             
<form method="POST" action="upload.html"  enctype="multipart/form-data">                                       
<input type="file" name="fichier" />                                                                       
<input type="text" name="toto" value="plouf" />                                                            
<select style="" name="civilite">                                                                          
<option>Madame</option> …
```
=> Fix #127 bad handling of upload forms

Dockerfile
@devl00p now we use python 3.9 in production, you can drop the 3.7/3.8 support if you need.
=> Update dockerfile to use bullseye

tests/net/test_page.py
This adds a test for the make_absolute function of file page.py before a possible refactor:
```
$ pylint wapitiCore/net/page.py
************* Module wapitiCore.net.page
wapitiCore/net/page.py:355:4: R0911: Too many return statements (9/6) (too-many-return-statements)
wapitiCore/net/page.py:721:4: R0912: Too many branches (41/40) (too-many-branches)
```
I noticed that some results are strange to me:
Shouldn't:
- `'http://base.url/with_folder' + '.'` be `'http://base.url/with_folder'` instead of `http://base.url/` ?
- `'http://base.url' + '/..//'` be `''` instead of `'http://base.url/'` ?
- `'http://base.url' + './wrong_folder/../good_folder/'` be `'http://base.url/'` instead of `'http://base.url/good_folder/'` ?
Maybe the function …
=> Add test for net/page

tests/web/test_crawl.py, wapitiCore/main/wapiti.py
=> Wapiti: clear stop_event at start of browse and attack methods

.github/workflows/main.yml
The CI has currently a problem due to the module `pylint` which has a ModuleNotFoundError inside of it. (https://github.com/wapiti-scanner/wapiti/runs/4351531830?check_suite_focus=true)
```txt
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/pylint_ignore/__main__.py", line 44, in <module>
from pylint.message.message_handler_mix_in import MessagesHandlerMixIn
ModuleNotFoundError: No module named 'pylint.message.message_handler_mix_in'
```
https://github.com/PyCQA/pylint/issues/5390  
To fix it, I have changed the `pylint` version to an anterior one.
=> Changed the pylint module to an anterior version due to a ModuleNotFoundError problem inside of it

INSTALL.md
I noticed a little inaccuracy in the instructions about using a virtual Python environment, in the section about activating the venv.
Please see the commit message.
_Thank you for maintaining and sharing the fabulous Wapiti by the way !_
=> [INSTALL.md] fix activation command for bash/sh

wapitiCore/attack/mod_drupal_enum.py
Fixed a false positive of the drupal_enum attack when it is launched on an URL that redirects to another one  
Example: `wapiti -u http://cyberwatch.fr -m drupal_enum`
N/A
=> Fixed a false positive of the drupal_enum attack

wapitiCore/attack/mod_csrf.py
Allow Wapiti to confirm Django has submitted the correct anti-CSRF form POST field.
This setting is not configurable within Django, so there’s no way for a developer to change the field’s name to match one of the tokens in the list.
=> Add Django’s CSRF HTML form name to the token list

tests/attack/test_mod_drupal_enum.py, wapitiCore/attack/mod_drupal_enum.py
When the page tested returns anything but 200, the result should be ignored
=> Fix drupal detection when return code is not 200

tests/attack/test_mod_log4shell.py, wapitiCore/attack/mod_log4shell.py
Improved the Log4Shell module to attack Apache Solr.
A docker has been created to test this feature.  
To run the server: `docker run -p 8080:8080 julientd/apache-solr-log4shell:latest` (it uses the version 8.9)
To run wapiti: `wapiti -u http://localhost:8983/ -m log4shell`
N/A
=> Improved the Log4Shell module to attack Apache Solr

tests/net/test_page.py, wapitiCore/net/page.py
Sometimes Wapiti crawls URLs in the meta tag, but the tag can be written in three different formats.  
Currently, we can only detect URLs with one specific formatting, and in this PR, I have added the two other types.  
The three types:  
The URL is written without any quotes. (already supported)
```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=http://test.com/" />
<title>Foobar</title>
</head>
<body>
<h1>hello world</h1>
</body>
</html>
```
The URL is written with simple quotes. (added support in this pr)
```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0;url='http://test.com/'" />
<title>Foobar</title>
</head>
<body>
<h1>hello world</h1>
</body>
</html>
```
The URL is written with double quotes. (added support in this pr)
```html …
```
=> Fixed the html_redirections function to adapt to every type of http-equiv meta tag and retrieve URLs

wapitiCore/main/wapiti.py
Currently, when we want to update a specific module we need to pass --update as an argument to wapiti, but it will update every module.
In this PR, I have added the possibility for the user to choose what module to update, it works the same as the attack module selector (moduleA,moduleB or all).  
Example: `wapiti --update all` or `wapiti --update wapp,nikto`
fixes #254
=> Modified the --update flag to permits the user to choose what modules to update

wapitiCore/attack/mod_backup.py, wapitiCore/attack/mod_drupal_enum.py, wapitiCore/attack/mod_exec.py, wapitiCore/attack/mod_file.py, wapitiCore/attack/mod_methods.py, wapitiCore/attack/mod_permanentxss.py, wapitiCore/attack/mod_sql.py, wapitiCore/attack/mod_takeover.py, wapitiCore/attack/mod_timesql.py, wapitiCore/attack/mod_wp_enum.py, wapitiCore/attack/mod_xss.py, wapitiCore/attack/mod_xxe.py, wapitiCore/net/page.py
Currently, Wapiti uses hardcoded status codes to verify if a request is successful or not.  
In this pull request, I have added 5 methods to determine if the status of a request is:  
- successful (2xx status codes)
- redirect (3xx status codes)
- error (4xx and 5xx status codes)
- client_error (4xx status codes)
- server_error (5xx status codes)
I have replaced these hardcoded status codes with these methods.
fixes #253
=> Replaced hard-coded status code to a wrapper function

tests/attack/test_mod_drupal_enum.py, tests/attack/test_mod_wp_enum.py, wapitiCore/attack/mod_drupal_enum.py, wapitiCore/attack/mod_wp_enum.py
Currently, when technology is found a vulnerability payload will be saved, but the problem is that some modules will save a payload as an addition, so for the same content, it will be split into two different categories.  
In this pull request, I have changed the type of payload for all the technology detection to an addition.
Also, when a version is found it is registered as a vulnerability, and when a technology is found it is registered as an addition.
N/A
=> Changed the payload type for the technology detection to addition instead of vulnerability

wapitiCore/attack/mod_http_headers.py, wapitiCore/definitions/http_headers.py
The X-XSS-Protection header has been deprecated.
This PR removes the associated check.
=> Deprecate X-XSS-Protection header

tests/attack/test_mod_drupal_enum.py, wapitiCore/attack/mod_drupal_enum.py
Cette PR vise à limiter certains faux positifs que l'on récupère sur des sites qui acceptent les requêtes sur /sites et /misc/test/error, et qui nous font dire qu'on a du Drupal en face.
Or, c'est pas des éléments discriminants super pertinents, car en plus la plupart des sites Drupal bien configurés ont le /sites qui renvoie du 403.
Le plus propre est donc de se concentrer sur les fichiers JS où là un code 200 peut légitimer le fait de dire que c'est du Drupal.
Je vous laisse regarder le tout pour voir si mon interprétation est correcte :).
Si c'est le cas, alors je vous laisse faire les modifs éventuelles, et rebase + merger le tout !
=> Drupal : retirer requêtes /sites /misc/test/error

tests/cli/test_options.py
These tests verify that modules are properly passed from the command line to the `Wapiti().update` method.
The test is intended to fail with the error reported at #305.
=> Add tests to check CLI `--update` command

tests/cli/test_options.py, wapitiCore/main/wapiti.py
Running `wapiti --update` is failing because the persister and crawler are not initialized. This is an attempt to fix #305.
This PR must be merged after #306.
=> Ensure Persister and Crawler are initialized before updating modules

tests/attack/test_mod_wapp.py, wapitiCore/wappalyzer/wappalyzer.py
The update of [Wappalyzer](https://github.com/wapiti-scanner/wappalyzer) some days ago broke some tests. This PR is an attempt to fix them.
Many tests failed because the current implementation of wappalyer.py does not support a list of regular expressions in field `url` of the technology file. However, Wappalyzer specifies multiple URLs for [ActiveCampaign](https://github.com/wapiti-scanner/wappalyzer/blob/main/src/technologies/a.json#L721). As a consequence, the regular expression was `["\\.activehosted\\.com", "\\.ac-page\\.com"]`, matching every request beginning with `http` for instance.
This resolved all the failing tests except two which were failing because less technologies were identified. As it is too hard to identify what is not identified anymore, technologies that should be …
=> Fix failing wapp tests

tests/attack/test_mod_htp.py, tests/attack/test_mod_log4shell.py, tests/attack/test_mod_nikto.py, tests/attack/test_mod_wapp.py, wapitiCore/attack/attack.py, wapitiCore/main/wapiti.py, wapitiCore/net/sql_persister.py, wapitiCore/wappalyzer/wappalyzer.py
Fixes crash when wapiti is called without `HOME` and `USERPROFILE` environment variables. It is caused by `os.path.joins` when a home directory is None.
Reproduce using: `env -i wapiti --version` > gives error
It can be resolved by providing HOME environment variable such as:
`env -i HOME=/root wapiti --version` > prints version.
Environment variables can be missing due to different isolation approaches such as a slim Docker image or an isolated shell.
This PR/commit fixes the issue by defaulting to `/home` directory that's Linux/Unix standard when an environment variable is missing. This way the crash is avoided.
=> Fix crash when missing environment variables

wapitiCore/main/wapiti.py, wapitiCore/net/auth.py, wapitiCore/parsers/commandline.py
Some web authentication mechanisms rely on using tokens received from xml/json responses or set using javascript.
Some websites also may ask for human validation (solving a captcha, giving the answer to a simple question, etc)
Even if a focus is made to improve authentication, Wapiti will never be able to support all auth mechanisms hence the need of providing a way for users to bring their own auth scripts to Wapiti.
The way it works is:
- specify a Python script using `--auth-script` option
- the script must have an async function called run with the following prototype:
```python
async def run(crawler_configuration: CrawlerConfiguration, auth_url: str, headless: str = "no")
```
It is up to the script to do whatever it needs to solve the authentication.
At the end, the script should …
=> Plugin mechanism to support custom and/or complicated website authentication

Dockerfile.headless
This merges the three RUN instructions into one layer and moved the removal of the content of `/tmp` at the end. Files
geckodriver.tar.gz and firefox.tar.bz2 are now removed. This reduces the image size from 663MB to 582MB (-13%).
/assign me
=> Remove temporary files in Docker headless image

tests/attack/test_mod_htp.py, wapitiCore/attack/mod_drupal_enum.py, wapitiCore/attack/mod_htp.py
htp module has several drawbacks:
* it is slow
* inconsistency in sqlite DB may generate crashes (see below)
* a range can be given while there is a single matching version
* some version strings are odd (eg: `from 10.0.0-alpha1 to start` for Drupal)
* there are frequent false positives
`ValueError: '4.2.1-rc2' is not in list` for Wordpress
```
sqlite> select * from version where technology = "WordPress" and version like '4.2.1%';
|WordPress|4.2.1
|WordPress|4.2.10
|WordPress|4.2.11
|WordPress|4.2.12
|WordPress|4.2.13
|WordPress|4.2.14
|WordPress|4.2.15
|WordPress|4.2.16
|WordPress|4.2.17
|WordPress|4.2.18
|WordPress|4.2.19
```
So it looks like a version is known for a given hash for that version is not part of the `version` table
Detected magento2 technology seems to match versions from …
=> Rework htp module

.github/workflows/main.yml
Update php7.4 to php8.1 in github actions since Ubuntu image moved from Ubuntu 20.04 to Ubuntu 22.04.
=> Update php7.4 to php8.1 in github actions

wapitiCore/definitions/http_only.py
Retrait du code WSTG relatif à HSTS pour les tests sur les mauvais attributs de cookies.
=> Fix bad WSTG code for bad cookie attribute

tests/cli/test_options.py, wapitiCore/main/wapiti.py
The handling of the `--update` flag is done before the handling of `--proxy` and `--tor`. As a result, the Crawler is
not configured to use the proxy when it tries to download the ressources required to update the modules.
Let's handle `--proxy` and `--tor` just before `--update`.
Closes #354
=> Use option `--proxy` and `--tor` with `--update`

tests/cli/test_options.py
The variable `mock_update` is already defined with a pytest fixture. There is no need to create it again inside a `with` bloc.
Furthermore, patching `sys.exit` ensures that the pytest command does not exit while running the test, but replacing `sys.exit` with a no-op means that the program won't stop after the update. As a consequence, the test execute all the attack modules. Using `pytest.raises` instead to catch the exception ensure the program ends after the update. This reduces the execution time of the test from 3s to 0.6s.
=> Speed up `--update` option test

setup.py
`pipenv graph` saying pydantic is only used by sslyze, let's put it in the `extra` dependencies for sslyze
=> set pydantic as sslyze extra in setup.py

wapitiCore/attack/mod_http_headers.py
Allow-from is an obsolete directive that no longer works in modern browsers.
=> Remove allow-from directive

wapitiCore/attack/mod_crlf.py
Quickfix to issue #402 
The module CRLF encode its payload unecessarily due to the mutator already doing it, removing the quote function from urllib.parse and its import does the job.
=> fixing double encoding on CRLF module

tests/attack/test_mod_methods.py, wapitiCore/attack/mod_methods.py
This PR is an answer for the issue #374 
It allows testing uncommon methods when they are detected with the OPTIONS method. Only methods with a different body content or a different server return code than the GET method will be listed. Methods returning a 405 error code (method not allowed) will also be ignored.
```Bash
wapiti -u https://misbehaving.site/anything -m methods --flush-session  
██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗██████╗
██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║╚════██╗
██║ █╗ ██║███████║██████╔╝██║   ██║   ██║ █████╔╝
██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║ ╚═══██╗
╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║██████╔╝
╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝╚═════╝  
Wapiti 3.1.7 (wapiti-scanner.github.io)
[*] Saving scan state, please wait...
[*] Launching module …
```
=> improving methods module and tests about it

.github/workflows/main.yml, Dockerfile.test
This MR features simple operations to reduce the test docker image.
With these changess, we build a 40% lighter image.
First, we regroup all apt install lines, so we can remove cache on the
same layer.
Then we remove pip3 cache, which is absolutely not negligible.
=> Reduce image test size

tests/wappalyzer/test_wappalyzer.py, wapitiCore/wappalyzer/wappalyzer.py
This MR in an echo to #413 
As said in the previous MR, sometimes in the database you can find empty values for some keys, for example in the header of the following JSON:
```JSON
"Akamai": {
"cats": [
31
],
"description": "Akamai is global content delivery network (CDN) services provider for media and software delivery, and cloud security solutions.",
"headers": {
"X-Akamai-Transformed": "",
"X-EdgeConnect-MidMile-RTT": "",
"X-EdgeConnect-Origin-MEX-Latency": ""
},
"icon": "Akamai.svg",
"pricing": [
"poa"
],
"saas": true,
"website": "http://akamai.com"
}
```
It means that we are looking for the keys instead of a regex value, and the work to recognize keys instead of values has started [here](https://github.com/wapiti-scanner/wapiti/blob/9c91017c016ec82df9f0ebf78cd2040a34b1c93b/wapitiCore/ …
=> quickfix key comparing

tests/web/test_network_issues.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_timesql.py, wapitiCore/net/crawler.py, wapitiCore/net/intercepting_explorer.py
Fix issue #394.
* I fix the network issues with a new configuration in `crawler.py` : 
```python
self._timeout = httpx.Timeout(timeout, read=None)
```
I did many tests to decide how to do. And here is some element to compare why None is better : 
Here with 10s in read timeout
Here with None in read timeout
The crawler is faster and crawl more URL than with 10s timeout. There is no chance to be stuck with the response delay because connect, pool and write timer are set to default or -t option.
* I also set a new param in different send request to allow the overwriting of the new crawler configuration for some modules like `timesql` and change the `read=None` to the -t or the default value.
* I change the timeout in headless crawler to fit with the -t option instead of constant value.
* I …
=> Fix #394: Network issues and crawlers improvements

pyproject.toml
Fix the issue #424.
Module httpx-ntlm is now installed by default.
=> Fix httpx-ntlm import issue from issue #424

tests/attack/test_mod_permanentxss.py, tests/attack/test_mod_xss_advanced.py, tests/data/xss/no_js_possible.php, wapitiCore/attack/mod_permanentxss.py, wapitiCore/attack/mod_xss.py, wapitiCore/data/attacks/xssPayloads.ini, wapitiCore/definitions/html_injection.py, wapitiCore/definitions/stored_html_injection.py, wapitiCore/model/__init__.py, wapitiCore/net/xss_utils.py
Idea I wanted to implement for quite some time: in some cases a WAF can block our JS payloads but HTML injection is still possible. This is often the indication that XSS is still possible but would require more work (obfuscation, etc)
The aim of that PR is to add a payload without JS and use it as a fallback if no JS payloads succeeded before.
I also fixed some bugs I discovered in `mod_permanentxss` and added some tests
=> Detect HTML injection in xss modules via non-js payload

tests/attack/test_mod_methods.py, wapitiCore/attack/mod_methods.py
Made some changes to mod_methods to address several issues:
- module said it was comparing the response with the one for GET which was not always the case
- as many report entries that interesting HTTP methods allowed
- very verbose output
- some common behavior not filtered (for example CONNECT without argument usually gives a 400 error)
Also added a check to report presence of TRACE is activated on the server
=> Rework mod_methods

Dockerfile, openssl_conf
Le changement de version de pip induit un problème concernant les env « externally managed »
```
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.11/README.venv for more information.
note: If you believe this is a mistake, please …
```
=> Passer l'image wapiti en debian 12

tests/attack/test_mod_wp_enum.py, wapitiCore/attack/mod_wp_enum.py
Add XML content-type verification in Wordpress version detection method since some WordPress might force a redirection to php file instead of XML file in some cases.
=> Add XML content-type verification in wp_enum

wapitiCore/parsers/html_parser.py, wapitiCore/wappalyzer/wappalyzer.py
Still pursuing my work on #413 
I found out that with headers and meta having multiple values for the same attribute, the wapp module miss technologies. 
Let's admit a response has 2 headers Server (example 1) :
```
Server : this 
Server : that
```
Or (example 2) :
```
Server : this, that
```
The code used to concatenate each value from attributes in a dictionary with a single string that way:
```Python
{
"Server": "this, that"
}
```
Which will make some regexes fail: admitting we can detect a technology thanks to its server attribute ``that`` by its regex, which is ``^that$``. It will not work as the regex is expecting the string to start and end with this word. As this behavior comes from HTTPX, you can find [more information here](https://www.python-httpx.org/quickstart/#response-header …
=> wappalyzer accept multiple headers and meta values

tests/attack/test_mod_wapp.py, tests/integration/test_mod_wapp/assertions/wapp_other_mock_index.wiki.jsp.html.json, wapitiCore/wappalyzer/wappalyzer.py
Still patching #413 
Now we have a comparison with keys when values are empty, but as described [here](https://github.com/wapiti-scanner/wapiti/blob/2484cde92120bf7df2298768afa8df5ccaa070c5/wapitiCore/wappalyzer/wappalyzer.py#L90-L92) all keys from meta, headers, cookies and dom are lowercased when normalizing the database. 
This is not the case with keys inputted in the module from the content. This fix lower all keys on the fly as soon as we compare them. 
Unit tests will come in a separated MR for every previous MR I made
```JSON
"Open Journal Systems": {
"cats": [
50
],
"cookies": {
"OJSSID": ""
},
"cpe": "cpe:2.3:a:public_knowledge_project:open_journal_systems:*:*:*:*:*:*:*:*",
"description": "Open Journal Systems (OJS) is an open-source software application for managing and …
```
=> Fix keys lowering in wapp module

tests/integration/check.sh, tests/integration/run.sh
Those are 2 patches for the integration test system:
- Variables expansions in strings are normalized with curvy braces
- a debug mode has been implemented to show the logs of all containers while there will all be silent in normal mode (except Wapiti)
TL;DR: see commits titles
=> changes on run.sh and check.sh

wapitiCore/attack/mod_exec.py
I noticed invariable issues with time-based payload in mod_exec : they always report vulnerabilities.
THe bug was introduced with the move to the new INI parser, we just need a check to ignore time basedpayloads if no timeout occurred
=> mod_exec: Skip time based payloads if no timeout occurred

doc/integration_system.md, tests/integration/init_test.sh, tests/integration/test_crawler_auth/docker-compose.setup.yml, tests/integration/test_crawler_redirect/docker-compose.setup.yml, tests/integration/test_mod_backup/docker-compose.setup.yml, tests/integration/test_mod_brute_login_form/docker-compose.setup.yml, tests/integration/test_mod_buster/docker-compose.setup.yml, tests/integration/test_mod_cookieflags/docker-compose.setup.yml, tests/integration/test_mod_crlf/docker-compose.setup.yml, tests/integration/test_mod_csp/docker-compose.setup.yml, tests/integration/test_mod_csrf/docker-compose.setup.yml, tests/integration/test_mod_drupal_enum/docker-compose.setup.yml, tests/integration/test_mod_exec/docker-compose.setup.yml, tests/integration/test_mod_file/docker-compose.setup.yml, tests/integration/test_mod_htaccess/docker-compose.setup.yml, tests/integration/test_mod_http_headers/docker-compose.setup.yml, tests/integration/test_mod_https_redirect/docker-compose.setup.yml, tests/integration/test_mod_log4shell/docker-compose.setup.yml, tests/integration/test_mod_methods/docker-compose.setup.yml, tests/integration/test_mod_permanentxss/docker-compose.setup.yml, tests/integration/test_mod_redirect/docker-compose.setup.yml, tests/integration/test_mod_shellshock/docker-compose.setup.yml, tests/integration/test_mod_sql/docker-compose.setup.yml, tests/integration/test_mod_ssrf/docker-compose.setup.yml, tests/integration/test_mod_timesql/docker-compose.setup.yml, tests/integration/test_mod_wapp/docker-compose.setup.yml, tests/integration/test_mod_wp_enum/docker-compose.setup.yml, tests/integration/test_mod_xss/docker-compose.setup.yml, tests/integration/test_mod_xxe/docker-compose.setup.yml
Added a script tool to generate default configuration when doing integration tests
The documentation has been updated about that and as Docker shorthands are now hardcoded in the script, I pruned the unecessary ones in the various ``docker-compose.setup.yml`` files
=> Integration test utility maker

tests/data/logged_in_failed_explicit.html, tests/data/logged_in_failed_implicit.html, tests/parsers/test_html_parser.py, wapitiCore/parsers/html_parser.py
Answer to #317 @tarraschk 
TL;DR: This commit raise a false flag as soon as it detects error messages from the response, and unit tests have been added.
This is only a small improvement, but we can only go little by little to improve this feature, since knowing if we are logged in regardless of which website we are on is a thought challenge. 
Unless someone has a genuine idea, I leave here things that already have been explored:
- Checking redirections by replaying the request on the login page: may not work because some websites doesn't redirect when you are logged in, and doesn't redirect either when you fail to log in
- Checking cookies state before and after the attempt of login: may work but should be implemented cautiously by exploring a large amount of cases (some websites uses …
=> Better detection is_logged_in

tests/attack/test_mod_timesql.py
Fix errors in timesql unit test.
Timeout test was unstable for test_timesql_detection() and test_timesql_false_positive().
=> Fix errors in timesql unit test

wapitiCore/controller/wapiti.py, wapitiCore/parsers/commandline.py
Modifie la valeur par défaut du timeout pour les sites web les plus lents
Note : cela ne pénalise pas les scans de la plupart des sites, car on n'atteint pas le timetout.
Cela ne concerne donc que les sites lents, qui en l'état ne sont pas correctement scannés.
Cette modification devrait donc améliorer les analyses de sites "pas très performants" avec la config par défaut.
=> Update default timeout for slow websites

wapitiCore/main/getcookie.py, wapitiCore/parsers/commandline.py
Correct a mistake in help menu : 
Change `PORT` for `{no,hidden,visible}`
=> Correct a mistake in help menu about headless

tests/attack/test_mod_buster.py, tests/attack/test_mod_exec.py, tests/attack/test_mod_file.py, tests/attack/test_mod_nikto.py, tests/attack/test_mod_timesql.py, wapitiCore/attack/attack.py, wapitiCore/attack/mod_buster.py, wapitiCore/attack/mod_drupal_enum.py, wapitiCore/attack/mod_exec.py, wapitiCore/attack/mod_file.py, wapitiCore/attack/mod_nikto.py, wapitiCore/attack/mod_timesql.py, wapitiCore/attack/mod_wp_enum.py, wapitiCore/main/wapiti.py
Add max-attack-time check for time-consuming modules.
Fix https://github.com/wapiti-scanner/wapiti/issues/498
=> Add time check for time-consuming modules

Dockerfile.headless
Upgrade the Dockerfile for headless version with:
- Debian from 11 to 12
- Firefox from 105.0 to 118.0
- gecko drive from 0.31.0 to 0.33.0
=> Upgrade headless docker with latest debian, firefox and geckodriver

Pipfile.lock
Had some strange errors after updating the repo:
```
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
httpx (>=0.21.*)
~~~~~~~^
✘ Locking Failed! 
```
Deleted the lockfile  then pipenv lock again
=> just update pipenv lock

.github/workflows/main.yml
Updating deprecated actions used in CI workflows. 
The more recent node versions. 
updated actions : 
- setup-python : v1/v2 => v4
- checkout: v2 => v4
- codecov: v1 => v3
- setup-buildx: v1 => v3
=> Update deprecated Actions

tests/mutation/test_json_mutator.py, wapitiCore/attack/attack.py, wapitiCore/mutation/json_mutator.py, wapitiCore/net/web.py
What it does :
- adds a mutator to inject payloads in body of HTTP requests when encoding is set to application/json
What it does not :
- inject payloads in URL parameters (stuff is kept for the classic mutator)
- makes the module attack json requests
- prevent modules from using the other mutators on json requests
- make sure json based requests are passed by the interceptor to modules
- refactor all mutators to put them in the new mutations package
- etc
=> JSON Mutator

wapitiCore/mutation/json_mutator.py
=> fix pylint json_mutator

.github/workflows/main.yml
=> GH Actions Security update

wapitiCore/attack/mod_wapp.py
In some cases, headless version detection will provide false positive on version value. For instance with Chart.js, the JS command `Chart` will result in a JS function.
So now it ensures whether a version is wanted or not for each JS command. For instance, Chart.js is still detected with the `Chart` command but without version.
=> Fix headless wapp version detection

Dockerfile.headless
Upgrade firefox and geekodriver in the headless docker image.
- Upgrade firefox from 118.0 to 124.0
- Upgrade geekodriver from 0.33.0 to 0.34.0
=> Update firefox and geekodrive to the last version in Dockerfile.headless

wapitiCore/net/intercepting_explorer.py
Fix clean method for headless explorer.
`queue.join()` was blocking in most cases waiting for `queue` to be emptied but it was not done.
Now it just ensures that `queue` is empty, no more `join` needed
=> Fix headless explorer clean method

tests/cli/test_options.py, wapitiCore/main/wapiti.py, wapitiCore/parsers/swagger.py
Fix the out of scope issue with swagger option.
=> Fix the out of scope issue with swagger option

.github/workflows/main.yml, README.rst, doc/ChangeLog_Wapiti, doc/FAQ.md, pyproject.toml, tests/attack/test_mod_ssl.py, tests/data/ssl/broken_ssl.xml, wapitiCore/attack/mod_ssl.py
Theer is still an issue related to certificate transparency logs.
Can't tell at the moment if crt.sh is broken or if I should do things  differently.
=> Use sslscan in place of sslyze

pyproject.toml, tests/attack/test_mod_wapp.py, tests/cve/test_cve.py, tests/data/wapp/categories.json, tests/data/wapp/cve.json, tests/data/wapp/groups.json, tests/data/wapp/mysql.json, tests/data/wapp/php.json, tests/data/wapp/wordpress.json, tests/integration/test_mod_wapp/assertions/wapp_backbonejs_index.html.json, tests/integration/test_mod_wapp/assertions/wapp_bootstrap_index.html.json, tests/integration/test_mod_wapp/assertions/wapp_jquery_index.html.json, tests/integration/test_mod_wapp/assertions/wapp_other_mock_index.wiki.jsp.html.json, tests/integration/test_mod_wapp/assertions/wapp_react_index.html.json, tests/integration/test_mod_wapp/assertions/wapp_vuejs_index.html.json, tests/integration/test_mod_wapp/behavior.json, tests/integration/wapiti/Dockerfile.integration, tests/integration/wapiti/templates_and_data.py, wapitiCore/attack/cve/checker.py, wapitiCore/attack/mod_wapp.py, wapitiCore/definitions/vulnerable_software_version.py, wapitiCore/main/log.py, wapitiCore/main/wapiti.py
- Download on the fly CVE data from wapiti-scanner/nvd-web-cves/ for a specific software when a version is detected. Data is JSON compressed with lzma (XZ)
- Use python `packaging` library for version comparison
- Adds a new finding called "Vulnerable software" which brings some CVE info (severity and description)
- The most recent CVSS format found is used for each CVE
- List of monitored softwares is hardcoded
- Separate wapp update logic from nvd update logic to ease testing
- Fix some issues present in mod_wapp, notably the categories.json and groups.json files were downloaded 27 times each due to bad indentation
- Fix some tests for mod_wapp, notably some assertions were lacking parenthesis to be effective
- Adds unit and integration tests for the new CVE finding
=> Add CVE findings

doc/cookies_and_scripts_auth.md, tests/net/test_crawler.py, wapitiCore/net/crawler.py
Saw since https://github.com/wapiti-scanner/wapiti/commit/85097cb80acb671d6063ea1c5ca3fb4d5522c967#diff-d7e9c3756fcd51d905c37cb6d0f0ce60e24934ff30e015bde1b6a354d7e11edcR339 that requests may be sent with the "content-type" header specifying an empty value.
The MR fix that and also removes async_send that is directly handled by async_request now.
=> crawler: fix empty enctype case

wapitiCore/attack/mod_exec.py, wapitiCore/data/attacks/execPayloads.ini
The rules for the ID command injection attacks were too permissive and would lead to several false positives.
Basically, when trying an injection with the `id` command, Wapiti would check if `id=` was available in the results. However, anything that contained `id=` would lead to a false positive, for instance `uuid=`.
Thus, I changed the rules for the id payload, in order to improve its results.
Also, I changed the comment at line 3, which said that rules were tested with a boolean AND when there were multiple case, but it was a boolean OR since a commit 9 months ago.
I tested the mod on the lab https://portswigger.net/web-security/os-command-injection/lab-simple and it still finds vulnerabilities.
=> Fix false positives on ID command injections attacks

.github/workflows/main.yml, .gitlab-ci.yml, README.rst, pyproject.toml, tests/attack/test_mod_ssl.py, tests/integration/wapiti/Dockerfile.integration
Adds Python 3.12 in pyproject.tom and also in Gitlab CI
I had to explicitely add setuptools as a dependency for Wapiti to work (guess it was previously installed from a removed dependency and worked that way)
=> Support Python 3.12
